openapi: 3.0.0
info:
  title: swagger_test_api
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
      description: ''
